---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: flask-app
          #imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_ROOT_PASSWORD 
              value: "1905" 
            - name: MYSQL_PORT_3306_TCP_ADDR
              value: mysql-service
            - name: MYSQL_PORT_3306_TCP_PORT
              value: "3306"
            - name: MYSQL_INSTANCE_NAME
              value: flaskapp   
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30007
 